// week 5/handson_08_vue/student-portal-vue/src/components/Header.vue
<script setup>
import { RouterLink } from 'vue-router';
import { useEnrollmentStore } from '../stores/enrollment';

const store = useEnrollmentStore();
</script>

<template>
  <header style="display: flex; justify-content: space-between; padding: 1rem;">
    <h1>Student Portal</h1>
    <nav style="display: flex; gap: 1rem;">
      <RouterLink to="/">Home</RouterLink>
      <RouterLink to="/courses">Courses</RouterLink>
      <RouterLink to="/profile">Profile ({{ store.enrolledCourses.length }})</RouterLink>
    </nav>
  </header>
</template>

// week 5/handson_05_06_react/student-portal-react/src/components/Header.jsx
import { Link } from 'react-router-dom';
import { useSelector } from 'react-redux';

function Header({ siteName }) {
  const enrolledCourses = useSelector(state => state.enrollment.enrolledCourses);

  return (
    <header style={{ display: 'flex', justifyContent: 'space-between', padding: '1rem' }}>
      <h1>{siteName}</h1>
      <nav style={{ display: 'flex', gap: '1rem' }}>
        <Link to="/courses">Courses</Link>
        <Link to="/profile">Profile ({enrolledCourses.length})</Link>
      </nav>
    </header>
  );
}

export default Header;
